slam_toolbox:
  ros__parameters:
    transform_publish_period: 0.1
    map_update_interval: 1.0
    resolution: 0.05
    max_laser_range: 12.0
    transform_timeout: 0.2
    tf_buffer_duration: 1.0
    stack_size_to_use: 10000000  # 10 MB

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.01  # 1 cm
    minimum_travel_heading: 0.01  # 0.5 deg
    scan_buffer_size: 3
    scan_buffer_maximum_scan_distance: 10.0
    link_scan_maximum_distance: 1.0
    do_loop_closing: true
